"""Integration tests for Phase 3 components in Mock Mode."""

import os
import unittest
import numpy as np
from jaxonflow.spec import KernelSpec
from jaxonflow.hardware import HardwareContext
from jaxonflow.compiler import KernelCompiler
from jaxonflow.verification import KernelVerifier
from jaxonflow.profiler import KernelProfiler
from jaxonflow.feedback import FeedbackTranslator

class TestPhase3Mock(unittest.TestCase):
    def setUp(self):
        # Force mock mode
        os.environ["JAXONFLOW_MOCK_GPU"] = "1"
        self.hardware = HardwareContext.detect()
        
    def test_end_to_end_mock_pipeline(self):
        """Test the full flow: Spec -> Compile -> Verify -> Profile -> Feedback."""
        
        # 0. Define a simple reference implementation (matmul)
        def reference_matmul(a, b):
            return np.dot(a, b)
            
        # 1. Create a KernelSpec
        spec = KernelSpec(
            operation="matmul",
            input_shapes=[(32, 64), (64, 32)],
            input_dtypes=["float32", "float32"],
            output_shape=(32, 32),
            output_dtype="float32",
            parameters={"m": 32, "n": 32, "k": 64},
            hardware=self.hardware,
            reference_impl=reference_matmul,
            framework="generic"
        )
        
        # 2. Compile (Mock)
        compiler = KernelCompiler()
        # Mock mode should just wrap the reference implementation
        # Note: in real usage, 'code' would be generated by Coder Agent.
        # Here we pass dummy code.
        dummy_code = "@triton.jit\ndef matmul_kernel(): pass"
        
        compile_result = compiler.compile_with_spec(dummy_code, spec)
        
        self.assertTrue(compile_result.success)
        self.assertIsNotNone(compile_result.kernel)
        self.assertIsNotNone(compile_result.kernel.callable)
        
        # 3. Verify (Mock)
        verifier = KernelVerifier()
        verify_result = verifier.verify(compile_result.kernel, spec)
        
        self.assertTrue(verify_result.correct)
        self.assertLess(verify_result.max_abs_error, 1e-5)
        
        # 4. Profile (Mock)
        profiler = KernelProfiler(self.hardware)
        profile_result = profiler.profile(compile_result.kernel, spec)
        
        self.assertGreater(profile_result.execution_time_us, 0)
        self.assertGreater(profile_result.speedup_vs_reference, 0)
        self.assertIn(profile_result.primary_bottleneck, ["memory", "compute", "latency"])
        
        # 5. Feedback
        translator = FeedbackTranslator()
        feedback = translator.translate(profile_result, self.hardware)
        
        self.assertIsInstance(feedback, str)
        self.assertIn("Speedup vs Reference", feedback)
        self.assertIn("Recommendations", feedback)

    def test_mock_compilation_failure_without_ref(self):
        """Test that mock compilation warns/fails gracefully without reference impl."""
        spec = KernelSpec(
            operation="unknown",
            input_shapes=[(10,)],
            input_dtypes=["float32"],
            output_shape=(10,),
            output_dtype="float32",
            reference_impl=None # Missing reference
        )
        
        compiler = KernelCompiler()
        compile_result = compiler.compile_with_spec("dummy", spec)
        
        # It succeeds in compilation (creating a dummy kernel)
        self.assertTrue(compile_result.success)
        
        # But verification should fail or execute dummy
        verifier = KernelVerifier()
        verify_result = verifier.verify(compile_result.kernel, spec)
        
        # Should fail because no reference to compare against
        self.assertFalse(verify_result.correct)
        self.assertIn("No reference implementation", verify_result.test_case_description)

if __name__ == "__main__":
    unittest.main()
